//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_GaragisteProjet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GaragisteProjetEntities : DbContext
    {
        public GaragisteProjetEntities()
            : base("name=GaragisteProjetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarnetEntretien> CarnetEntretien { get; set; }
        public virtual DbSet<Garagiste> Garagiste { get; set; }
        public virtual DbSet<Revision> Revision { get; set; }
        public virtual DbSet<Voiture> Voiture { get; set; }
    }
}
