//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_GaragisteProjet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garagiste
    {
        public Garagiste(int idGaragiste, string nomGaragiste, DateTime? dateFermeture, int? dureeFermeture, int? capacite, ICollection<Voiture> voiture)
        {
            IdGaragiste = idGaragiste;
            NomGaragiste = nomGaragiste;
            DateFermeture = dateFermeture;
            DureeFermeture = dureeFermeture;
            Capacite = capacite;
            Voiture = voiture;
        }


        public Garagiste()
        {
            this.Voiture = new HashSet<Voiture>();
        }
    
        public int IdGaragiste { get; set; }
        public string NomGaragiste { get; set; }
        public Nullable<System.DateTime> DateFermeture { get; set; }
        public Nullable<int> DureeFermeture { get; set; }
        public Nullable<int> Capacite { get; set; }
    
        public virtual ICollection<Voiture> Voiture { get; set; }

       
    }

}
