//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_GaragisteProjet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision
    {
        public int NumCarnet { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> Kilometrage { get; set; }
        public Nullable<int> DureeIntervention { get; set; }
    
        public virtual CarnetEntretien CarnetEntretien { get; set; }
    }
}
