//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_GaragisteProjet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voiture
    {
        public Voiture()
        {
            this.CarnetEntretien = new HashSet<CarnetEntretien>();
        }
    
        public int ImmatriculationVoiture { get; set; }
        public Nullable<int> IdGaragiste { get; set; }
        public string ModeleVoiture { get; set; }
        public string MarqueVoiture { get; set; }
        public string TypeVoiture { get; set; }
        public string Carburant { get; set; }
    
        public virtual ICollection<CarnetEntretien> CarnetEntretien { get; set; }
        public virtual Garagiste Garagiste { get; set; }
    }
}
